name: Update Versions

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to use for the extension (ex: 3.0.1).'
        required: true
        type: string
        default: ''

      branch:
        description: 'The target branch where the version update will be applied and the pull request will be merged into.'
        required: true
        type: string
        default: ''

      core-dependency:
        description: 'If a version is provided, update AEPCore dependency in gradle.properties (ex: 3.0.1).'
        required: false
        type: string
        default: ''

      edge-identity-dependency:
        description: 'If a version is provided, update AEPEdgeIdentity dependency in gradle.properties (ex: 3.0.1).'
        required: false
        type: string
        default: ''

      edge-consent-dependency:
        description: 'If a version is provided, update AEPEdgeConsent dependency in gradle.properties (ex: 3.0.1).'
        required: false
        type: string
        default: ''

      testutils-dependency:
        description: 'If a version is provided, update AEPTestUtils dependency in gradle.properties (ex: 3.0.1).'
        required: false
        type: string
        default: ''

jobs:
  update-versions:
    permissions:
      contents: write
    uses: timkimadobe/aepsdk-commons/.github/workflows/versions.yml@version-script-update
    with:
      version: ${{ github.event.inputs.version }}
      branch: ${{ github.event.inputs.branch }}
      dependencies: AEPCore ${{ github.event.inputs.core-dependency }}, AEPEdgeIdentity ${{ github.event.inputs.edge-identity-dependency }}, AEPEdgeConsent ${{ github.event.inputs.edge-consent-dependency }}, AEPTestUtils ${{ github.event.inputs.testutils-dependency }}
      paths: code/edge/src/main/java/com/adobe/marketing/mobile/EdgeConstants.java, code/gradle.properties
      update: true
      workflow_tag: gha-android-1.0.0
